CREATE DATABASE IF NOT EXISTS speedfast_db;
USE speedfast_db;

CREATE TABLE repartidor (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL
);
CREATE TABLE pedido (
	id INT AUTO_INCREMENT PRIMARY KEY,
	direccion VARCHAR(150) NOT NULL,
	tipo VARCHAR(30) NOT NULL,
	estado VARCHAR(20) NOT NULL,
    CHECK (tipo IN ('COMIDA', 'ENCOMIENDA', 'EXPRESS')),
    CHECK (estado IN ('PENDIENTE', 'EN_REPARTO', 'ENTREGADO'))
);
CREATE TABLE entrega (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_pedido INT NOT NULL,
	id_repartidor INT NOT NULL,
	fecha DATE NOT NULL,
	hora TIME NOT NULL,
	FOREIGN KEY (id_pedido) REFERENCES pedido(id),
	FOREIGN KEY (id_repartidor) REFERENCES repartidor(id)
);